trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
    checkLatest: true

- script: |
    npm install -g @angular/cli
    npm install
    ng build--prod
  displayName: 'build'
- task: Bash@3
  inputs:
    script: 'npm run test-ci'